<?php
require_once 'CRM/Core/Form.php';
/**
 * Form controller class
 *
 * @see http://wiki.civicrm.org/confluence/display/CRMDOC43/QuickForm+Reference
 */
class CRM_Cluster_Form_Cluster extends CRM_Core_Form {
  protected $cluster;
  protected $id;

  function preProcess() {
    if(!empty($_GET['id'])){
      $this->id = $_GET['id'];//CRM_Utils_Request::retrieve('id', 'Integer', CRM_core_DAO::$_nullObject, TRUE);
    }

    if(!empty($this->id)){
      $params['id'] = $this->id;
      $clusters = CRM_Cluster_BAO_Cluster::getValues($params);
      $this->cluster = $clusters[$this->id];
      $this->cluster['country_id'] = $this->cluster['country_id'];
    }

    parent::preProcess(); // TODO: Change the autogenerated stub
  }

  function setDefaultValues() {
    return $this->cluster;
  }

  public function buildQuickForm() {
    $this->addFormElements();
    parent::buildQuickForm();
  }

  public function postProcess() {
    $values = $this->exportValues();

    if(!empty($values['id']) && is_int((int)$values['id'])){
      $this->cluster['id'] = (int)$values['id'];
    }

    $this->cluster['label'] = $values['label'];
    $this->cluster['name'] = $values['name'];

    if(!empty($values['country_id'])){
      $this->cluster['country_id'] = $values['country_id'];
    } else {
      $this->cluster['country_id'] = 'NULL';
    }
    if($values['is_active'] == '1') {
      $this->cluster['is_active'] = $values['is_active'];
    } else {
      $this->cluster['is_active'] = '0';
    }

    CRM_Cluster_BAO_Cluster::add($this->cluster);

    CRM_Utils_System::redirect('clusterlist?reset=1');

    parent::postProcess();
  }

  /**
   * Get the fields/elements defined in this form.
   *
   * @return array (string)
   */
  public function getRenderableElementNames() {
    // The _elements list includes some items which should not be
    // auto-rendered in the loop -- such as "qfKey" and "buttons".  These
    // items don't have labels.  We'll identify renderable by filtering on
    // the 'label'.
    $elementNames = array();
    foreach ($this->_elements as $element) {
      /** @var HTML_QuickForm_Element $element */
      $label = $element->getLabel();
      if (!empty($label)) {
        $elementNames[] = $element->getName();
      }
    }
    return $elementNames;
  }

  /**
   * Function to add form elements
   *
   * @access protected
   */
  protected function addFormElements() {
    $parentList = CRM_Cluster_Utils::getList(1);
    $this->add('hidden', 'id', $this->id);
    // add form elements
    $this->add('text', 'name', ts('Name'), array('size' => 128), FALSE);
    $this->add('text', 'label', ts('Label'), array('size' => 128), TRUE);
    $this->add('checkbox', 'is_active', ts('Is Active'), array(), FALSE);
    /*
      //This was originally meant for selecting multiple countries per cluster,
      //But pum deciced that each cluster is specific to that country even if it has the same name ¯\_(ツ)_/¯

      $countrySelect = $this->addElement('advmultiselect', 'countries', ts('Countries'), $this->getCountries(),
      array('id' => 'countries','class' => 'advmultselect', 'size' => 10, 'style' => 'width:auto;'),TRUE);

      $countrySelect->setButtonAttributes('add', array('value' => ts('Add country for this cluster')." >>"));
      $countrySelect->setButtonAttributes('remove', array('value' => "<< ".ts('Remove country for this cluster')));

    */

    $this->add('select', 'country_id', ts('Country'), array(NULL=>'- select -') + $this->getCountries(), FALSE);

    $this->addButtons(array(
      array('type' => 'next', 'name' => ts('Save'), 'isDefault' => TRUE),
      array('type' => 'cancel', 'name' => ts('Cancel'))));
    // export form elements
    $this->assign('elementNames', $this->getRenderableElementNames());
  }

  /**
   * Method to get available countries
   *
   * @return array
   */
  private function getCountries() {
    $result = array();
    try {
      $countries = civicrm_api3('Country', 'get', array(
        'version' => 3,
        'sequential' => 1,
        'rowCount' => 0
      ));

      foreach ($countries['values'] as $country) {
        $result[$country['id']] = $country['name'];
      }
    } catch (CiviCRM_API3_Exception $ex) {}

    return $result;
  }
}