SET NAMES 'utf8';

INSERT INTO civicrm.civicrm_pum_cluster(name, label, is_active, country_id) VALUES
('agriculture', 'Agriculture', 1, 1003),
('agri_incubator', 'Agri-incubator', 1, 1003),
('vocational_training_algeria', 'Vocational training', 1, 1003),
('dairy_armenia', 'Dairy', 1, 1011),
('fashion_textile', 'Fashion & Textile', 1, 1011),
('health_armenia', 'Health', 1, 1011),
('tourism_armenia', 'Tourism', 1, 1011),
('agri_horticulture_bangladesh', 'Agri- & Horticulture', 1, 1017),
('dairy_farming_processing', 'Dairy Farming & Processing', 1, 1017),
('health_care_services', 'Health Care Services', 1, 1017),
('it_business_consultancy', 'IT Business Consultancy', 1, 1017),
('poultry_farming', 'Poultry Farming', 1, 1017),
('cashew_honey_agri_products', 'Agri Products  (Nuts, cashew, honey, fruit, food)', 1, 1022),
('financial_marketing', 'Health, education, equipment, pharmacy', 1, 1022),
('health_sector_education_equipment_building', 'Metal, Building, Textiles', 1, 1022),
('metal_sector_re_use_and_repairs', 'Finance, Marketing, Hotellerie', 1, 1022),
('agriculture_arable_farming_forestry', 'Agriculture: Arable farming & Forestry', 1, 1025),
('dairy_cattle_dairy_production_farming', 'Dairy cattle & dairy production/farming', 1, 1025),
('hospitality_tourism_recreational_services', 'Hospitality: tourism & recreational services', 1, 1025),
('minerals', 'Minerals', 1, 1025),
('mining', 'Mining', 1, 1025),
('animal_cattle_breeding_and_poultry', 'Animal/cattle breeding and poultry', 1, 1034),
('foodchain_agriculture', 'Foodchain Agriculture', 1, 1034),
('mango_s', 'Mango''s', 1, 1034),
('agri__horticulture_colombia', 'Agri-& Horticulture', 1, 1048),
('bso', 'BSO', 1, 1048),
('coffee', 'Coffee', 1, 1048),
('textile_colombia', 'Textile', 1, 1048),
('bakery_ethiopia', 'Bakery', 1, 1070),
('beekeeping_ethiopia', 'Beekeeping', 1, 1070),
('dairy_animal_feed', 'Dairy/Animal Feed', 1, 1070),
('health_ethiopia', 'Health', 1, 1070),
('incubators_ethiopia', 'Incubators', 1, 1070),
('leather_ethiopia', 'Leather', 1, 1070),
('milk_processing_products', 'Milk processing & Products', 1, 1070),
('poultry_ethiopia', 'Poultry', 1, 1070),
('waste_ethiopia', 'Waste', 1, 1070),
('hospitality_gambia', 'Hospitality', 1, 1213),
('poultry_gambia', 'Poultry', 1, 1213),
('cosmetics_shea_nuts', 'Cosmetics: Shea nuts', 1, 1083),
('horticulture', 'Horticulture', 1, 1083),
('hospitality', 'Hospitality', 1, 1083),
('poultry_ghana', 'Poultry', 1, 1083),
('agri_and_horticulture_india', 'Agri- and Horticulture', 1, 1101),
('dairy_stockbreeding', 'Dairy & Stockbreeding', 1, 1101),
('female_enterpreneurship_in_rural_india', 'Female enterpreneurship in rural India', 1, 1101),
('health_care_india', 'Health Care', 1, 1101),
('incubators_india', 'Incubators', 1, 1101),
('metal_chemical', 'Metal & Chemical', 1, 1101),
('textiles_leather', 'Textiles & leather', 1, 1101),
('dairy_indonesia', 'Dairy', 1, 1102),
('food_industry', 'Food industry', 1, 1102),
('healthcare_indonesia', 'Healthcare', 1, 1102),
('horticulture_indonesia', 'Horticulture', 1, 1102),
('hospitality_indonesia', 'Hospitality', 1, 1102),
('textile_and_leather', 'Textile and leather', 1, 1102),
('waste', 'Waste', 1, 1102),
('agri_culture_and_agri_technology', 'Agri-culture and Agri-technology', 1, 1110),
('incubator_accelerator', 'Incubator/Accelerator', 1, 1110),
('tourism_jordan', 'Tourism', 1, 1110),
('dairy_stockbreeding_processing', 'Dairy & stockbreeding (-processing)', 1, 1112),
('health_care_kenya', 'Health care', 1, 1112),
('incubators_kenya', 'Incubators', 1, 1112),
('tourism_hospitality_kenya', 'Tourism & Hospitality', 1, 1112),
('vegetables_fruits_processing', 'Vegetables & fruits (-processing)', 1, 1112),
('water_waste', 'Water waste', 1, 1112),
('agriculture_and_food_processing', 'Agriculture and Food processing', 1, 1120),
('chemical_cleantech', 'Chemical & Clean technology', 1, 1120),
('ict', 'ICT', 1, 1120),
('farming_crops_fruits_and_vegetables', 'Farming: Crops, Fruits and vegetables', 1, 1133),
('farming_livestock', 'Farming: Livestock', 1, 1133),
('beekeeping_morocco', 'Beekeeping', 1, 1146),
('dairy_morocco', 'Dairy', 1, 1146),
('tadla_sustainable_dairy_sector', 'Tadla Sustainable Dairy Sector', 1, 1146),
('tourism_morocco', 'Tourism', 1, 1146),
('waste_morocco', 'Waste', 1, 1146),
('dairy_myanmar', 'Dairy', 1, 1035),
('fisheries_aquaculture_fish_processing', 'Fisheries: Aquaculture & Fish Processing', 1, 1035),
('horticulture_myanmar', 'Horticulture', 1, 1035),
('hospitality_tourism_myanmar', 'Hospitality & Tourism', 1, 1035),
('agriculture_nepal', 'Agriculture', 1, 1050),
('hospitality_tourism_nepal', 'Hospitality & Tourism', 1, 1050),
('incubators_nepal', 'Incubators', 1, 1050),
('agriculture_agri_industrial', 'Agriculture & Agri-industrial', 1, 1165),
('incubators_palestinian', 'Incubators', 1, 1165),
('tourism_palestinian', 'Tourism', 1, 1165),
('cocoa_chain', 'Cocoa Chain', 1, 1169),
('processing_of_dairy_products', 'Processing of dairy products', 1, 1169),
('tourism_hospitality_peru', 'Tourism & Hospitality', 1, 1169),
('agriculture_production_processing', 'Agriculture - Production & Processing', 1, 1170),
('constructions', 'Constructions', 1, 1170),
('incubators_and_business_support_organisations', 'Incubators and Business Support Organisations', 1, 1170),
('tourism_services', 'Tourism services', 1, 1170),
('environment_energy_solar_waste_water', 'Environment (Energy, solar, waste-/water)', 1, 1178),
('poultry_rwanda', 'Poultry', 1, 1178),
('tourism_rwanda', 'Tourism', 1, 1178),
('vocational_education_rwanda', 'Vocational Education', 1, 1178),
('circular_economy', 'Circular economy', 1, 1188),
('fruits_de_casamance', 'Fruits de Casamance', 1, 1188),
('local_cereals_for_local_food', 'Local cereals for local food', 1, 1188),
('onion_value_chain_senegal', 'Onion value chain Senegal', 1, 1188),
('agriculture_horticulture_south_africa', 'Agriculture & Horticulture', 1, 1196),
('building_construction_south_africa', 'Building & Construction', 1, 1196),
('hospitality_tourism_south_africa', 'Hospitality & Tourism', 1, 1196),
('metal_industries_south_africa', 'Metal Industries', 1, 1196),
('textiles_leathers', 'Textiles & Leathers', 1, 1196),
('vocational', 'Vocational', 1, 1196),
('waste_water_recycling', 'Waste (water) & Recycling', 1, 1196),
('food_beverage', 'Food & beverage', 1, 1199),
('tourism', 'Tourism', 1, 1199),
('area_development_construction_maintenance', 'Area development, construction & maintenance', 1, 1201),
('energy_water_waste_environment_suriname', 'Energy, water, waste & environment', 1, 1201),
('food_security_and_agriculture', 'Food security and agriculture', 1, 1201),
('health_suriname', 'Health', 1, 1201),
('tourism_hospitality_suriname', 'Tourism & hospitality', 1, 1201),
('trade_and_retail', 'Trade and retail', 1, 1201),
('vocational_training_suriname', 'Vocational training', 1, 1201),
('food_security_tanzania', 'Food security', 1, 1210),
('good_health_care', 'Good health care', 1, 1210),
('sustainable_building_construction', 'Sustainable building & construction', 1, 1210),
('value_chain_development_in_agriculture_for_sme_s', 'Value chain development in agriculture for SME\'s', 1, 1218),
('value_chain_development_in_livestock_for_sme_s', 'Value chain development in livestock for SME\'s', 1, 1218),
('dairy_uganda', 'Dairy', 1, 1223),
('healthcare_uganda', 'Healthcare', 1, 1223),
('horticulture_vegetables_fruits', 'Horticulture: Vegetables & fruits', 1, 1223),
('hotels', 'Hotels', 1, 1223),
('agri_horticulture_vietnam', 'Agri - & Horticulture', 1, 1233),
('animal_production_beekeeping_fisheries', 'Animal production, Beekeeping & Fisheries', 1, 1233),
('building_construction_vietnam', 'Building & Construction', 1, 1233),
('chemical_synthetic_materials', 'Chemical & synthetic materials', 1, 1233),
('food_beverages_production_vietnam', 'Food & beverages production', 1, 1233),
('incubators_vietnam', 'Incubators', 1, 1233),
('tourism_hospitality_vietnam', 'Tourism & Hospitality', 1, 1233),
('vocational_education_vietnam', 'Vocational Education', 1, 1233),
('business_support', 'Business support', 1, 1239),
('food_security_zambia', 'Food security', 1, 1239),
('hospitality_zambia', 'Hospitality', 1, 1239),
('horticulture_zimbabwe', 'Horticulture', 1, 1240),
('leather_zimbabwe', 'Leather', 1, 1240),
('tourism_zimbabwe', 'Tourism', 1, 1240);