SET NAMES 'utf8';

INSERT INTO civicrm.civicrm_pum_cluster(name, label, is_active, country_id) VALUES
('algeria_agriculture', 'Agriculture', 1, 1003),
('algeria_agri_incubator', 'Agri-incubator', 1, 1003),
('algeria_vocational_training_algeria', 'Vocational training', 1, 1003),
('armenia_dairy', 'Dairy', 1, 1011),
('armenia_fashion_textile', 'Fashion & Textile', 1, 1011),
('armenia_health', 'Health', 1, 1011),
('armenia_tourism', 'Tourism', 1, 1011),
('bangladesh_agri_horticulture', 'Agri- & Horticulture', 1, 1017),
('bangladesh_dairy_farming_processing', 'Dairy Farming & Processing', 1, 1017),
('bangladesh_health_care_services', 'Health Care Services', 1, 1017),
('bangladesh_it_business_consultancy', 'IT Business Consultancy', 1, 1017),
('bangladesh_poultry_farming', 'Poultry Farming', 1, 1017),
('benin_agri_products_nuts_cashew_honey_fruit_food', 'Agri Products (Nuts, cashew, honey, fruit, food)', 1, 1022),
('benin_finance_marketing_hotellerie', 'Finance, Marketing, Hotellerie', 1, 1022),
('benin_health_sector_education_equipment_pharmacy', 'Health sector, education, equipment, pharmacy', 1, 1022),
('benin_metal_building_textiles', 'Metal, Building, Textiles', 1, 1022),
('bolivia_agriculture_arable_farming_forestry', 'Agriculture: Arable farming & Forestry', 1, 1025),
('bolivia_dairy_cattle_dairy_production_farming', 'Dairy cattle & dairy production/farming', 1, 1025),
('bolivia_hospitality_tourism_recreational_services', 'Hospitality: tourism & recreational services', 1, 1025),
('bolivia_minerals', 'Minerals', 1, 1025),
('bolivia_mining', 'Mining', 1, 1025),
('burkina_faso_animal_cattle_breeding_and_poultry', 'Animal/cattle breeding and poultry', 1, 1034),
('burkina_faso_foodchain_agriculture', 'Foodchain Agriculture', 1, 1034),
('burkina_faso_mango_s', 'Mango''s', 1, 1034),
('colombia_agri__horticulture', 'Agri-& Horticulture', 1, 1048),
('colombia_bso', 'BSO', 1, 1048),
('colombia_coffee', 'Coffee', 1, 1048),
('colombia_textile', 'Textile', 1, 1048),
('ethiopia_bakery', 'Bakery', 1, 1070),
('ethiopia_beekeeping', 'Beekeeping', 1, 1070),
('ethiopia_dairy_animal_feed', 'Dairy/Animal Feed', 1, 1070),
('ethiopia_health', 'Health', 1, 1070),
('ethiopia_incubators', 'Incubators', 1, 1070),
('ethiopia_leather', 'Leather', 1, 1070),
('ethiopia_milk_processing_products', 'Milk processing & Products', 1, 1070),
('ethiopia_poultry', 'Poultry', 1, 1070),
('ethiopia_waste', 'Waste', 1, 1070),
('gambia_hospitality', 'Hospitality', 1, 1213),
('gambia_poultry', 'Poultry', 1, 1213),
('ghana_cosmetics_shea_nuts', 'Cosmetics: Shea nuts', 1, 1083),
('ghana_horticulture', 'Horticulture', 1, 1083),
('ghana_hospitality', 'Hospitality', 1, 1083),
('ghana_poultry', 'Poultry', 1, 1083),
('india_agri_and_horticulture', 'Agri- and Horticulture', 1, 1101),
('india_dairy_stockbreeding', 'Dairy & Stockbreeding', 1, 1101),
('india_female_enterpreneurship_in_rural', 'Female enterpreneurship in rural India', 1, 1101),
('india_health_care', 'Health Care', 1, 1101),
('india_incubators', 'Incubators', 1, 1101),
('india_metal_chemical', 'Metal & Chemical', 1, 1101),
('india_textiles_leather', 'Textiles & Leather', 1, 1101),
('indonesia_dairy', 'Dairy', 1, 1102),
('indonesia_food_industry', 'Food industry', 1, 1102),
('indonesia_healthcare', 'Healthcare', 1, 1102),
('indonesia_horticulture', 'Horticulture', 1, 1102),
('indonesia_hospitality', 'Hospitality', 1, 1102),
('indonesia_textile_and_leather', 'Textile and leather', 1, 1102),
('indonesia_waste', 'Waste', 1, 1102),
('jordan_agri_culture_and_agri_technology', 'Agri-culture and Agri-technology', 1, 1110),
('jordan_incubator_accelerator', 'Incubator/Accelerator', 1, 1110),
('jordan_tourism', 'Tourism', 1, 1110),
('kenya_dairy_livestock_breeding_processing', 'Dairy & Livestock breeding (-processing)', 1, 1112),
('kenya_tourism_hospitality', 'Tourism & Hospitality', 1, 1112),
('kenya_vegetables_fruits_processing', 'Vegetables & fruits (-processing)', 1, 1112),
('lebanon_agriculture_and_food_processing', 'Agriculture and Food processing', 1, 1120),
('lebanon_chemical_cleantech', 'Chemical & Clean technology', 1, 1120),
('lebanon_ict', 'ICT', 1, 1120),
('mali_farming_crops_fruits_and_vegetables', 'Farming: Crops, Fruits and vegetables', 1, 1133),
('mali_farming_livestock', 'Farming: Livestock', 1, 1133),
('morocco_beekeeping', 'Beekeeping', 1, 1146),
('morocco_dairy', 'Dairy', 1, 1146),
('morocco_tadla_sustainable_dairy_sector', 'Tadla Sustainable Dairy Sector', 1, 1146),
('morocco_tourism', 'Tourism', 1, 1146),
('morocco_waste', 'Waste', 1, 1146),
('myanmar_dairy', 'Dairy', 1, 1035),
('myanmar_fisheries_aquaculture_fish_processing', 'Fisheries: Aquaculture & Fish Processing', 1, 1035),
('myanmar_horticulture', 'Horticulture', 1, 1035),
('myanmar_hospitality_tourism', 'Hospitality & Tourism', 1, 1035),
('nepal_agriculture', 'Agriculture', 1, 1150),
('nepal_hospitality_tourism', 'Hospitality & Tourism', 1, 1150),
('nepal_incubators', 'Incubators', 1, 1150),
('palestinian_agriculture_agri_industrial', 'Agriculture & Agri-industrial', 1, 1165),
('palestinian_incubators', 'Incubators', 1, 1165),
('palestinian_tourism', 'Tourism', 1, 1165),
('peru_cocoa_chain', 'Cocoa Chain', 1, 1169),
('peru_processing_of_dairy_products', 'Processing of dairy products', 1, 1169),
('peru_tourism_hospitality', 'Tourism & Hospitality', 1, 1169),
('philippines_agriculture_production_processing', 'Agriculture - Production & Processing', 1, 1170),
('philippines_constructions', 'Constructions', 1, 1170),
('philippines_incubators_and_business_support_organisations', 'Incubators and Business Support Organisations', 1, 1170),
('philippines_tourism_services', 'Tourism services', 1, 1170),
('rwanda_environment_energy_solar_waste_water', 'Environment (Energy, solar, waste-/water)', 1, 1178),
('rwanda_poultry_rwanda', 'Poultry', 1, 1178),
('rwanda_tourism_rwanda', 'Tourism', 1, 1178),
('rwanda_vocational_education_rwanda', 'Vocational Education', 1, 1178),
('senegal_circular_economy', 'Circular economy', 1, 1188),
('senegal_fruits_de_casamance', 'Fruits de Casamance', 1, 1188),
('senegal_local_cereals_for_local_food', 'Local cereals for local food', 1, 1188),
('senegal_onion_value_chain_senegal', 'Onion value chain Senegal', 1, 1188),
('southafrica_agriculture_horticulture', 'Agriculture & Horticulture', 1, 1196),
('southafrica_building_construction', 'Building & Construction', 1, 1196),
('southafrica_hospitality_tourism', 'Hospitality & Tourism', 1, 1196),
('southafrica_metal_industries', 'Metal Industries', 1, 1196),
('southafrica_textiles_leathers', 'Textiles & Leathers', 1, 1196),
('southafrica_vocational', 'Vocational', 1, 1196),
('southafrica_waste_water_recycling', 'Waste (water) & Recycling', 1, 1196),
('srilanka_food_beverage', 'Food & beverage', 1, 1199),
('srilanka_tourism', 'Tourism', 1, 1199),
('suriname_area_development_construction_maintenance', 'Area development, construction & maintenance', 1, 1201),
('suriname_energy_water_waste_environment', 'Energy, water, waste & environment', 1, 1201),
('suriname_food_security_and_agriculture', 'Food security and agriculture', 1, 1201),
('suriname_health', 'Health', 1, 1201),
('suriname_tourism_hospitality', 'Tourism & hospitality', 1, 1201),
('suriname_trade_and_retail', 'Trade and retail', 1, 1201),
('suriname_vocational_training', 'Vocational training', 1, 1201),
('tanzania_food_security', 'Food security', 1, 1210),
('tanzania_good_health_care', 'Good health care', 1, 1210),
('tanzania_sustainable_building_construction', 'Sustainable building & construction', 1, 1210),
('tunisia_value_chain_development_in_agriculture_for_sme_s', 'Value chain development in agriculture for SME\'s', 1, 1218),
('tunisia_value_chain_development_in_livestock_for_sme_s', 'Value chain development in livestock for SME\'s', 1, 1218),
('uganda_dairy', 'Dairy', 1, 1223),
('uganda_healthcare', 'Healthcare', 1, 1223),
('uganda_horticulture_vegetables_fruits', 'Horticulture: Vegetables & fruits', 1, 1223),
('uganda_hotels', 'Hotels', 1, 1223),
('vietnam_agri_horticulture', 'Agri - & Horticulture', 1, 1233),
('vietnam_animal_production_beekeeping_fisheries', 'Animal production, Beekeeping & Fisheries', 1, 1233),
('vietnam_building_construction', 'Building & Construction', 1, 1233),
('vietnam_chemical_synthetic_materials', 'Chemical & synthetic materials', 1, 1233),
('vietnam_food_beverages_production', 'Food & beverages production', 1, 1233),
('vietnam_incubators', 'Incubators', 1, 1233),
('vietnam_tourism_hospitality', 'Tourism & Hospitality', 1, 1233),
('vietnam_vocational_education', 'Vocational Education', 1, 1233),
('zambia_business_support', 'Business support', 1, 1239),
('zambia_food_security', 'Food security', 1, 1239),
('zambia_hospitality', 'Hospitality', 1, 1239),
('zimbabwe_horticulture', 'Horticulture', 1, 1240),
('zimbabwe_leather', 'Leather', 1, 1240),
('zimbabwe_tourism', 'Tourism', 1, 1240);